[build]
builder = "nixpacks"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.regions]
eu-west = 1

[deploy.resources]
cpu = 2
memory = 512 